"""Add Fantasy Team Model

Revision ID: 3cb4d803c9ad
Revises: 4ac9026ffc4c
Create Date: 2025-02-25 19:44:01.995328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb4d803c9ad'
down_revision: Union[str, None] = '4ac9026ffc4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
