"""Fix user_id type in FantasyTeam

Revision ID: 5a214bfa3afc
Revises: 5828090c947a
Create Date: 2025-02-25 20:04:39.914681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a214bfa3afc'
down_revision: Union[str, None] = '5828090c947a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
