"""Fix user_id UUID issue

Revision ID: f690a5ae3a05
Revises: 5a214bfa3afc
Create Date: 2025-02-26 11:12:54.267650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f690a5ae3a05'
down_revision: Union[str, None] = '5a214bfa3afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fantasy_points')
    op.drop_table('fantasy_teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasy_teams',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('driver_1', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('driver_2', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('driver_3', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('driver_4', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('constructor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('budget_remaining', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fantasy_teams_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='fantasy_teams_pkey')
    )
    op.create_table('fantasy_points',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('race_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fantasy_points_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='fantasy_points_pkey')
    )
    # ### end Alembic commands ###
