"""make team nullable

Revision ID: ffed598e1e26
Revises: f690a5ae3a05
Create Date: 2025-03-29 15:33:40.690941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffed598e1e26'
down_revision: Union[str, None] = 'f690a5ae3a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fantasy_points')
    op.drop_table('fantasy_teams')
    op.alter_column('users', 'team',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'team',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('fantasy_teams',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('driver_1', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('driver_2', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('driver_3', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('driver_4', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('constructor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('budget_remaining', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fantasy_teams_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='fantasy_teams_pkey')
    )
    op.create_table('fantasy_points',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('race_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fantasy_points_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='fantasy_points_pkey')
    )
    # ### end Alembic commands ###
